spring.application.name=task-master

spring.application.name=TaskTrackerSystem

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/task_master_db
spring.datasource.username=task_master_user
spring.datasource.password=task_master_password@1
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# JWT
jwt.secret=szdsgfdkhxoqqpp2579cwe7bv0q0rd226hddoaoao5shdasdf7801j
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# Attachments
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
